dropdown-behavior.html

@dbatiste: this seems to occur quite frequently, where the `_targetChanged` is firing before the DOM is ready so `getElementById()` returns null, even though the element is there.

deferring fetching of target in case it's not in the DOM at init time

---

demo/dropdown.html
dropdown.html

@dbatiste
Couldn't just remove the absolute positioning, since the balloon tail was relying on it a little bit.
This change essentially makes this possible: `<d2l-dropdown style="min-width:200px; max-width:500px;">`, which is a pretty nice way to size it. If we want, we could even have a default max/min width... otherwise it'll take up as much room as the content needs.
Also needed to add that extra `div` so that content which exceeds the max-width (if set) get clipped somehow. Could set `overflow:hidden` on the other container because then it would clip the tail.

allowing dropdown to be sized properly

---

dropdown-behavior.html

@dlockhart : suggesting we change this to use setTimeout.
When Polymer's async method is used, the `document.activeElement` is the `body` at this point (the focus hasn't been moved to other elements in the dropdown) and so the dropdown closes.  When `setTimeout` is used `document.activeElement` is the element that is expected to have the focus (ex. a link in the dropdown).

Changing to use setTimeout instead of async.

---

d2l-menu.html
demo/menu.html

When rendering in a context that already provides border, it is desirable to not display side borders on menus/menu-items.  This `no-side-borders` attribute effectively makes the side borders transparent when item is not hovered/focused, and also removes the border radius.  As per design, the side borders are still displayed on hover/focus.
@dlockhart , @capajon : does this attribute make sense given nav context?  Or, do you think there is more that needs to change?

 Add "no-side-borders" menu attribute for menus.

---

hierarchical-view-behavior.html

This change updates the auto sizing logic for hierarchical view: if the view is not displayed then it will be cloned to body and positioned offscreen where its height can be obtained.

If root view not displayed then clone to get dimensions.

---

menu-item-behavior.html

@capajon : does this make sense?  The purpose here is to defer initialize until template is resolved, and to only set child-view specific properties if the item has at least one non-template child.  Initialize will be called regardless.

Update so menu-item:initialize will always be called.

---

hierarchical-view-behavior.html

Fire `resize` event if light-dom changes for active view in order to trigger container size update.

Fire resize event if light-dom nodes change for active view.

---

dropdown-behavior.html

Add focus capture to `document.body` when dropdown is open to catch cases where the blur event fired (which normally captures focus loss for the dropdown) but the activeElement is still in the dropdown.  This case arises when a user used `Ctrl-F` to open browser's Find prompt and begins typing at the prompt.  The blur handler still catches cases where the user clicks away from the dropdown.

Add focus capture.

---

README.md
bower.json
d2l-dropdown-menu.html
d2l-dropdown.html
dropdown-behavior.html
test/dropdown.html

If `no-auto-focus` attribute is applied the component will not automatically focus on first focusable descendant.  Useful for cases where the content of the dropdown may not be ready yet.  Default behavior is to automatically apply focus to the first focusable descendant.

Adding no-auto-focus option.

---

d2l-menu-item-link.html
d2l-menu-item-return.html
d2l-menu-item-styles.html
d2l-menu-item.html
demo/menu-custom-components.html

This change updates the styles for `d2l-menu-item`, `d2l-menu-item-return`, and `d2l-menu-item-link` so that they display ellipsis when they overflow.  It was necessary to shift some padding to line-height so that the bottom of characters don't get cut off (ex. "g").
.

Fix to show overflow ellipsis.  

---

d2l-menu-item-behavior.html

@dbatiste This change does seem to solve the issue of creating the element and then appending to it after.
The compare is sure confusing looking - I recommend just looking at the updated ready and __initialize functions without comparison markings. :)
If this looks good I'll have to do a patch release.

Initialize again if menu items change

---

dropdown-behavior.html
test/dropdown.html

@dbatiste 
This solves 2 issues:
- when a click occurs _inside_ the dropdown on an element which can't receive focus (e.g. the dropdown itself), `document.activeElement` becomes the `<body>` which caused the existing auto-focus code to close the dropdown
- the click handling code was using `document.activeElement` instead of the click target to check if it was a descendant

Auto-Close Fixes

---

d2l-dropdown-content-behavior.html
d2l-dropdown-content.html
d2l-dropdown-menu.html

These can be kind of nice to have on general content as well, if the content is scrollable. Moving them out of the d2l-dropdown-menu and into the underlying behavior so that they're available in all cases.
Fixes #76.
Is this worth being able to turn on/off with an attribute? It's fairly innocuous, but idk, might be circumstances where we explicitly don't want it?

Move content-top and content-top to content-behavior

---

bower.json
d2l-dropdown-content-behavior.html
test/dropdown-content.html

When a dropdown has an ancestor that's focusable, that ancestor may (in all cases I've observed, will) gain focus when an empty area of a dropdown is clicked. This adds an additional check in the focus handler that the focused element isn't a focused ancestor, so that autoclose is deferred to the click handler instead as in other cases.

Fix case where dropdown closes when clicked if it has focusable ancestor

---

d2l-dropdown-content-behavior.html
d2l-dropdown-menu.html
d2l-dropdown-opener-behavior.html

Behavior change: only focus on content of dropdown is the user activated the opener via keyboard.  If the user clicks with mouse, do not auto focus on dropdown content, leave focus on opener.

US80149 - Only apply focus in content if keyboard/enter.

---

d2l-dropdown-content-behavior.html

In earlier implementation, content.style.overflowY = 'auto' will not be triggered until we resize the window. However, when user clicks "Load More" button, the event won't be fired which caused no scrollbar introduced.

uses overflow-y auto for d2l-dropdown-content

---

d2l-dropdown-button.html

This necessary to override the explicit ferrite color defined at part of `d2l-icon` styles.  Otherwise, the primary button menu opener has a ferrite icon on blue button.

Update color of primary opener icon.

---

bower.json
d2l-dropdown-content-behavior.html

Fix for when shadow-dom is enabled and dropdown is in shadow-dom of another component.  Without this, dropdown closes when users click on items inside dropdown before the click is triggers on the target, resulting in it being impossible to activate items inside the dropdown with mouse.

Fix auto-close for when shadow-dom is enabled.

---

bower.json
d2l-dropdown-context-menu.html
d2l-dropdown-opener-behavior.html

button PR related to `active` coming shortly
The `active` attribute is so that when the menu is open, the button doesn't go back to the default state (e.g., shows hover behaviour)

use d2l-button-icon in d2l-dropdown-context-menu

---

d2l-dropdown-context-menu.html
d2l-dropdown-more.html

This results in consistent sizing for openers and buttons (42x42px).

Use consistent sizing for dropdown openers.

---

d2l-dropdown-content-behavior.js
test/dropdown-content.html

Default dropdown behavior is to focus on the first focusable element upon opening the dropdown with the keyboard.  In IE/Edge however, the `focus()` call needs to be bumped to the next frame, possibly because the dropdown may not be made visible yet.  This seems to be a crazy bug with IE/Edge that it ends up triggering the click event on the focused element.  To side-step this, we can bump `focus()` of the first focusable element to the next frame.

Fix to apply focus on open so that IE/Edge don't crazily invoke click

---

package.json

We want to stop using `iron-iconset-svg` when we move to Core/icons. This is seemingly not needed or referenced anywhere in dropdown.

removing unneeded dependency

---

d2l-dropdown-content-behavior.js
test/dropdown-content.html

Allows ESC key to be pressed to close the dropdown even if it doesn't currently have focus. This is needed in the navbar builder case because it opens the dropdown with `no-auto-focus`, but then currently pressing ESC doesn't close it.

use dismissible helper

---

.eslintrc.json
d2l-dropdown-content-behavior.js
d2l-dropdown-opener-behavior.js

Update the Polymer 3 dropdown to have a compatible interface with the lit dropdown so that breaking changes can be fixed before switching over to the lit version.
1. [`forceRender` is now `async` in the lit version of the Dropdown.](https://github.com/BrightspaceUI/core/blob/master/components/dropdown/dropdown-content-mixin.js#L186) This will allow anywhere `forceRender` is called to be updated to use promises.
2. [My Courses accesses the internal dropdown content using `queryEffectiveChildren` which doesn't exist in lit.](https://github.com/Brightspace/d2l-my-courses-ui/blob/master/src/d2l-all-courses.js#L693) I will be updating this to instead call [`__getContentElement` which has been updated to get the slot's `assignedNodes`.](https://github.com/BrightspaceUI/core/blob/master/component …

Lit Compatibility
